package com.example.demo;

import java.math.BigDecimal;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;

import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Service
public class EmailService {
	
	private JavaMailSender javaMailSender;

    public EmailService(JavaMailSender javaMailSender) {
        this.javaMailSender = javaMailSender;
    }

    public void sendOrderConfirmationEmail(String recipient, String orderNumber, List<OrderSummary> orderItems, BigDecimal totalPrice, String collPoint) {
        MimeMessage message = javaMailSender.createMimeMessage();
        MimeMessageHelper helper;
        try {
            helper = new MimeMessageHelper(message, true);
            helper.setFrom("accounts@madhurams.co.uk");
            helper.setTo(recipient);
            helper.setSubject("Order Confirmation");
            helper.setText(getOrderConfirmationHtml(orderNumber, orderItems, totalPrice, collPoint), true);
           
        } catch (MessagingException e) {
            throw new RuntimeException("Failed to send order confirmation email", e);
        }
        javaMailSender.send(message);
        System.out.println("Email sent with message: " + message);
    }

    private String getOrderConfirmationHtml(String orderNumber, List<OrderSummary> orderItems, BigDecimal totalPrice, String collPoint) {
        StringBuilder sb = new StringBuilder();
        
        DateFormat Date = DateFormat.getDateInstance();
        Calendar cals = Calendar.getInstance();
        String currentDate = Date.format(cals.getTime());
        
        sb.append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
        		+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" style=\"font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'\">\r\n"
        		+ "    <head>\r\n"
        		+ "        <meta charset=\"UTF-8\">\r\n"
        		+ "        <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n"
        		+ "        <meta name=\"x-apple-disable-message-reformatting\">\r\n"
        		+ "        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
        		+ "        <meta content=\"telephone=no\" name=\"format-detection\">\r\n"
        		+ "        <title>New email template 2023-03-13</title>\r\n"
        		+ "        <!--[if (mso 16)]><style type=\"text/css\">     a {text-decoration: none;}     </style><![endif]-->\r\n"
        		+ "        <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]-->\r\n"
        		+ "        <!--[if gte mso 9]><xml> <o:OfficeDocumentSettings> <o:AllowPNG></o:AllowPNG> <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> </xml><![endif]-->\r\n"
        		+ "        <!--[if !mso]><!-- -->\r\n"
        		+ "        <link href=\"https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap\" rel=\"stylesheet\">\r\n"
        		+ "        <!--<![endif]-->\r\n"
        		+ "        <style type=\"text/css\">\r\n"
        		+ "            #outlook a {\r\n"
        		+ "                padding: 0;\r\n"
        		+ "            }\r\n"
        		+ "\r\n"
        		+ "            .es-button {\r\n"
        		+ "                mso-style-priority: 100!important;\r\n"
        		+ "                text-decoration: none!important;\r\n"
        		+ "            }\r\n"
        		+ "\r\n"
        		+ "            a[x-apple-data-detectors] {\r\n"
        		+ "                color: inherit!important;\r\n"
        		+ "                text-decoration: none!important;\r\n"
        		+ "                font-size: inherit!important;\r\n"
        		+ "                font-family: inherit!important;\r\n"
        		+ "                font-weight: inherit!important;\r\n"
        		+ "                line-height: inherit!important;\r\n"
        		+ "            }\r\n"
        		+ "\r\n"
        		+ "            .es-desk-hidden {\r\n"
        		+ "                display: none;\r\n"
        		+ "                float: left;\r\n"
        		+ "                overflow: hidden;\r\n"
        		+ "                width: 0;\r\n"
        		+ "                max-height: 0;\r\n"
        		+ "                line-height: 0;\r\n"
        		+ "                mso-hide: all;\r\n"
        		+ "            }\r\n"
        		+ "\r\n"
        		+ "            @media only screen and (max-width: 600px) {\r\n"
        		+ "                p, ul li, ol li, a {\r\n"
        		+ "                    line-height:150%!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                h1, h2, h3, h1 a, h2 a, h3 a {\r\n"
        		+ "                    line-height: 120%\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                h1 {\r\n"
        		+ "                    font-size: 40px!important;\r\n"
        		+ "                    text-align: center\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                h2 {\r\n"
        		+ "                    font-size: 20px!important;\r\n"
        		+ "                    text-align: center\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                h3 {\r\n"
        		+ "                    font-size: 18px!important;\r\n"
        		+ "                    text-align: center\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-header-body h1 a, .es-content-body h1 a, .es-footer-body h1 a {\r\n"
        		+ "                    font-size: 30px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-header-body h2 a, .es-content-body h2 a, .es-footer-body h2 a {\r\n"
        		+ "                    font-size: 26px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-header-body h3 a, .es-content-body h3 a, .es-footer-body h3 a {\r\n"
        		+ "                    font-size: 20px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-menu td a {\r\n"
        		+ "                    font-size: 16px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-header-body p, .es-header-body ul li, .es-header-body ol li, .es-header-body a {\r\n"
        		+ "                    font-size: 16px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-content-body p, .es-content-body ul li, .es-content-body ol li, .es-content-body a {\r\n"
        		+ "                    font-size: 16px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-footer-body p, .es-footer-body ul li, .es-footer-body ol li, .es-footer-body a {\r\n"
        		+ "                    font-size: 16px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-infoblock p, .es-infoblock ul li, .es-infoblock ol li, .es-infoblock a {\r\n"
        		+ "                    font-size: 12px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                *[class=\"gmail-fix\"] {\r\n"
        		+ "                    display: none!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3 {\r\n"
        		+ "                    text-align: center!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3 {\r\n"
        		+ "                    text-align: right!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3 {\r\n"
        		+ "                    text-align: left!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img {\r\n"
        		+ "                    display: inline!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-button-border {\r\n"
        		+ "                    display: block!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                a.es-button, button.es-button {\r\n"
        		+ "                    font-size: 20px!important;\r\n"
        		+ "                    display: block!important;\r\n"
        		+ "                    border-left-width: 0px!important;\r\n"
        		+ "                    border-right-width: 0px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-adaptive table, .es-left, .es-right {\r\n"
        		+ "                    width: 100%!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header {\r\n"
        		+ "                    width: 100%!important;\r\n"
        		+ "                    max-width: 600px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-adapt-td {\r\n"
        		+ "                    display: block!important;\r\n"
        		+ "                    width: 100%!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .adapt-img {\r\n"
        		+ "                    width: 100%!important;\r\n"
        		+ "                    height: auto!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p0 {\r\n"
        		+ "                    padding: 0!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p0r {\r\n"
        		+ "                    padding-right: 0!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p0l {\r\n"
        		+ "                    padding-left: 0!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p0t {\r\n"
        		+ "                    padding-top: 0!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p0b {\r\n"
        		+ "                    padding-bottom: 0!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p20b {\r\n"
        		+ "                    padding-bottom: 20px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-mobile-hidden, .es-hidden {\r\n"
        		+ "                    display: none!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                tr.es-desk-hidden, td.es-desk-hidden, table.es-desk-hidden {\r\n"
        		+ "                    width: auto!important;\r\n"
        		+ "                    overflow: visible!important;\r\n"
        		+ "                    float: none!important;\r\n"
        		+ "                    max-height: inherit!important;\r\n"
        		+ "                    line-height: inherit!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                tr.es-desk-hidden {\r\n"
        		+ "                    display: table-row!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                table.es-desk-hidden {\r\n"
        		+ "                    display: table!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                td.es-desk-menu-hidden {\r\n"
        		+ "                    display: table-cell!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-menu td {\r\n"
        		+ "                    width: 1%!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                table.es-table-not-adapt, .esd-block-html table {\r\n"
        		+ "                    width: auto!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                table.es-social {\r\n"
        		+ "                    display: inline-block!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                table.es-social td {\r\n"
        		+ "                    display: inline-block!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p5 {\r\n"
        		+ "                    padding: 5px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p5t {\r\n"
        		+ "                    padding-top: 5px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p5b {\r\n"
        		+ "                    padding-bottom: 5px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p5r {\r\n"
        		+ "                    padding-right: 5px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p5l {\r\n"
        		+ "                    padding-left: 5px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p10 {\r\n"
        		+ "                    padding: 10px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p10t {\r\n"
        		+ "                    padding-top: 10px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p10b {\r\n"
        		+ "                    padding-bottom: 10px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p10r {\r\n"
        		+ "                    padding-right: 10px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p10l {\r\n"
        		+ "                    padding-left: 10px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p15 {\r\n"
        		+ "                    padding: 15px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p15t {\r\n"
        		+ "                    padding-top: 15px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p15b {\r\n"
        		+ "                    padding-bottom: 15px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p15r {\r\n"
        		+ "                    padding-right: 15px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p15l {\r\n"
        		+ "                    padding-left: 15px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p20 {\r\n"
        		+ "                    padding: 20px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p20t {\r\n"
        		+ "                    padding-top: 20px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p20r {\r\n"
        		+ "                    padding-right: 20px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p20l {\r\n"
        		+ "                    padding-left: 20px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p25 {\r\n"
        		+ "                    padding: 25px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p25t {\r\n"
        		+ "                    padding-top: 25px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p25b {\r\n"
        		+ "                    padding-bottom: 25px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p25r {\r\n"
        		+ "                    padding-right: 25px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p25l {\r\n"
        		+ "                    padding-left: 25px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p30 {\r\n"
        		+ "                    padding: 30px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p30t {\r\n"
        		+ "                    padding-top: 30px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p30b {\r\n"
        		+ "                    padding-bottom: 30px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p30r {\r\n"
        		+ "                    padding-right: 30px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p30l {\r\n"
        		+ "                    padding-left: 30px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p35 {\r\n"
        		+ "                    padding: 35px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p35t {\r\n"
        		+ "                    padding-top: 35px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p35b {\r\n"
        		+ "                    padding-bottom: 35px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p35r {\r\n"
        		+ "                    padding-right: 35px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p35l {\r\n"
        		+ "                    padding-left: 35px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p40 {\r\n"
        		+ "                    padding: 40px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p40t {\r\n"
        		+ "                    padding-top: 40px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p40b {\r\n"
        		+ "                    padding-bottom: 40px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p40r {\r\n"
        		+ "                    padding-right: 40px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-m-p40l {\r\n"
        		+ "                    padding-left: 40px!important\r\n"
        		+ "                }\r\n"
        		+ "\r\n"
        		+ "                .es-desk-hidden {\r\n"
        		+ "                    display: table-row!important;\r\n"
        		+ "                    width: auto!important;\r\n"
        		+ "                    overflow: visible!important;\r\n"
        		+ "                    max-height: inherit!important\r\n"
        		+ "                }\r\n"
        		+ "            }\r\n"
        		+ "        </style>\r\n"
        		+ "    </head>\r\n"
        		+ "    <body style=\"width:100%;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0\">\r\n"
        		+ "        <div class=\"es-wrapper-color\" style=\"background-color:#C68B59\">\r\n"
        		+ "            <!--[if gte mso 9]><v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\"> <v:fill type=\"tile\" color=\"#C68B59\"></v:fill> </v:background><![endif]-->\r\n"
        		+ "            <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:white\">\r\n"
        		+ "                <tr>\r\n"
        		+ "                    <td valign=\"top\" style=\"padding:0;Margin:0\">\r\n"
        		+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content\" align=\"center\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\r\n"
        		+ "                            <tr>\r\n"
        		+ "                                <td class=\"es-info-area\" align=\"center\" style=\"padding:0;Margin:0\">\r\n"
        		+ "                                    <table class=\"es-content-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px\" bgcolor=\"#FFFFFF\">\r\n"
        		+ "                                        <tr>\r\n"
        		+ "                                            <td align=\"left\" style=\"Margin:0;padding-top:10px;padding-bottom:10px;padding-left:20px;padding-right:20px\">\r\n"
        		+ "                                                <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
        		+ "                                                    <tr>\r\n"
        		+ "                                                        <td align=\"center\" valign=\"top\" style=\"padding:0;Margin:0;width:560px\">\r\n"
        		+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
        		+ "                                                                <tr>\r\n"
        		+ "                                                                    <td align=\"center\" class=\"es-infoblock\" style=\"padding:0;Margin:0;line-height:14px;font-size:12px;color:#CCCCCC\">\r\n"
        		+ "                                                                    </td>\r\n"
        		+ "                                                                </tr>\r\n"
        		+ "                                                            </table>\r\n"
        		+ "                                                        </td>\r\n"
        		+ "                                                    </tr>\r\n"
        		+ "                                                </table>\r\n"
        		+ "                                            </td>\r\n"
        		+ "                                        </tr>\r\n"
        		+ "                                    </table>\r\n"
        		+ "                                </td>\r\n"
        		+ "                            </tr>\r\n"
        		+ "                        </table>\r\n"
        		+ "                        <table class=\"es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\r\n"
        		+ "                            <tr>\r\n"
        		+ "                                <td align=\"center\" style=\"padding:0;Margin:0\">\r\n"
        		+ "                                    <table class=\"es-content-body\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#ffffff;width:600px\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\">\r\n"
        		+ "                                        <tr>\r\n"
        		+ "                                            <td align=\"left\" style=\"padding:0;Margin:0;padding-top:35px;padding-bottom:40px\">\r\n"
        		+ "                                                <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
        		+ "                                                    <tr>\r\n"
        		+ "                                                        <td class=\"es-m-p0r\" valign=\"top\" align=\"center\" style=\"padding:0;Margin:0;width:600px\">\r\n"
        		+ "                                                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
        		+ "                                                                <tr>\r\n"
        		+ "                                                                    <td align=\"center\" style=\"Margin:0;padding-top:10px;padding-bottom:10px;padding-left:40px;padding-right:40px\">\r\n"
        		+ "                                                                        <h1 style=\"Margin:0;line-height:48px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:40px;font-style:normal;font-weight:bold;color:#38761d\">\r\n"
        		+ "                                                                            Madhurams\r\n"
        		+ "                                                                        </h1>\r\n"
        		+ "                                                                    </td>\r\n"
        		+ "                                                                </tr>\r\n"
        		+ "                                                            </table>\r\n"
        		+ "                                                        </td>\r\n"
        		+ "                                                    </tr>\r\n"
        		+ "                                                </table>\r\n"
        		+ "                                            </td>\r\n"
        		+ "                                        </tr>\r\n"
        		+ "                                    </table>\r\n"
        		+ "                                </td>\r\n"
        		+ "                            </tr>\r\n"
        		+ "                        </table>\r\n"
        		+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-content\" align=\"center\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\r\n"
        		+ "                            <tr>\r\n"
        		+ "                                <td align=\"center\" style=\"padding:0;Margin:0\">\r\n"
        		+ "                                    <table bgcolor=\"#ffffff\" class=\"es-content-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px\">\r\n"
        		+ "                                        <tr>\r\n"
        		+ "                                            <td align=\"left\" style=\"padding:0;Margin:0;padding-top:20px;padding-left:20px;padding-right:20px\">\r\n"
        		+ "                                                <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
        		+ "                                                    <tr>\r\n"
        		+ "                                                        <td align=\"center\" valign=\"top\" style=\"padding:0;Margin:0;width:560px\">\r\n"
        		+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
        		+ "                                                                <tr>\r\n"
        		+ "                                                                    <td align=\"left\" style=\"padding:0;Margin:0\">\r\n"
        		+ "                                                                      <div style=\"clear: both\">\r\n"
        		+ "                                                                        <h2 style=\"Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:16px;font-style:normal;font-weight:bold;color:#38761d;float:left\">Order Number:</h2>\r\n"
        		+ "                                                                        <h3 style=\"Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:16px;font-style:normal;font-weight:bold;color:#402218;float:left\">&nbsp;")
        		.append(orderNumber).append("</h3>\r\n"
        		+ "                                                                      </div>\r\n"
        		+ "                                                                    </td>\r\n"
        		+ "                                                                    <td align=\"left\" style=\"padding:0;Margin:0\">\r\n"
        		+ "\r\n"
        		+ "                                                                    </td>\r\n"
        		+ "                                                                </tr>  <tr>\r\n"
        		+ "                                                                    <td align=\"left\" style=\"padding:0;Margin:0\">\r\n"
        		+ "                                                                      <div style=\"clear: both\">\r\n"
        		+ "                                                                        <h2 style=\"Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:16px;font-style:normal;font-weight:bold;color:#38761d;float:left\">Order Date:</h2>\r\n"
        		+ "                                                                        <h3 style=\"Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:16px;font-style:normal;font-weight:bold;color:#402218;float:left\">&nbsp;")
        		.append(currentDate).append("</h3>\r\n"
        		+ "\r\n"
        		+ "                                                                      </div>\r\n"
        		+ "\r\n"
        		+ "                                                                    </td>\r\n"
        		+ "                                                                    <td align=\"left\" style=\"padding:0;Margin:0\">\r\n"
        		+ "\r\n"
        		+ "                                                                    </td>\r\n"
        		+ "                                                                </tr>\r\n"
        		+ "\r\n"
        		+ "                                                                <tr>\r\n"
        		+ "                                                                    <td align=\"left\" style=\"padding:0;Margin:0\">\r\n"
        		+ "                                                                      <div style=\"clear: both\">\r\n"
        		+ "                                                                        <h2 style=\"Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:16px;font-style:normal;font-weight:bold;color:#38761d;float:left\">Collection Point:</h2>\r\n"
        		+ "                                                                        <h3 style=\"Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:16px;font-style:normal;font-weight:bold;color:#402218;float:left\">&nbsp;")
                .append(collPoint).append("</h3>\r\n"
        		+ "\r\n"
        		+ "                                                                      </div>\r\n"
        		+ "\r\n"
        		+ "                                                                    </td>\r\n"
        		+ "                                                                    <td align=\"left\" style=\"padding:0;Margin:0\">\r\n"
        		+ "\r\n"
        		+ "                                                                    </td>\r\n"
        		+ "                                                                </tr>" 
        		+ "\r\n<tr>\r\n"
        		+ "\r\n"
        		+ "                                                                  <td style=\"padding-top:10px;\">  <p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:18px;color:#402218;font-size:14px\">\r\n"
        		+ "                                                                  Dear Customer,<br> Thanks for your order and it is now being processed. Please feel free to contact us with above reference number.</p></td></tr>"
        		+ "                                                            </table>\r\n"
        		+ "                                                        </td>\r\n"
        		+ "                                                    </tr>\r\n"
        		+ "                                                </table>\r\n"
        		+ "                                            </td>\r\n"
        		+ "                                        </tr>\r\n"
        		+ "\r\n"
        		+ "<!-- Start Here -->\r\n");        			
        		sb.append("<tr>\r\n"
        				+ "                                          <td class=\"esdev-adapt-off\" align=\"left\" style=\"padding:0;Margin:0;padding-left:20px;padding-right:20px;padding-top:30px\">\r\n"
        				+ "                                          <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" id=\"templateColumns\">\r\n");
        		
        				sb.append("<tr>\r\n"
        				+ "\r\n"
        				+ "                                                  <td align=\"center\" valign=\"top\" width=\"50%\" class=\"templateColumnContainer\">\r\n"
        				+ "                                                      <table border=\"0\" cellpadding=\"10\" cellspacing=\"0\" width=\"100%\">\r\n");
        				for (OrderSummary item : orderItems) {
        				sb.append("<tr>\r\n"
        				+ "                                                            <td style=\"Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:12px;font-style:normal;font-weight:bold;color:#402218\">\r\n"
        				+ "                                                                <h2>")
        				.append(item.getProductName()).append("</h2>\r\n"
        				+ "                                                            </td>\r\n"
        				+ "                                                            <td \">\r\n"
        				+ "                                                                <p>")
        				.append(item.getQuantity()).append("</p>\r\n"
        				+ "                                                            </td>\r\n"
        				+ "                                                            <td >\r\n"
        				+ "                                                                <p>")
        				.append(item.getUnitPrice()).append("</p>\r\n"
        				+ "                                                            </td>\r\n"
        				+ "                                                            <td >\r\n"
        				+ "                                                                <p>")
        				.append(item.getItemTotal()).append("</p>\r\n"
        				+ "                                                            </td>\r\n"
        				+ "                                                        </tr>\r\n");
        				}
        				sb.append("</table>\r\n"
        				+ "                                                  </td>\r\n"
        				+ "                                              </tr>\r\n");
        				sb.append("</table>\r\n"
        				+ "                                        </td>\r\n"
        				+ "                                        </tr>");	
        			
        			
        			
//        		sb.append("\r\n"
//        		+ "                                        <tr>\r\n"
//        		+ "                                            <td class=\"esdev-adapt-off\" align=\"left\" style=\"padding:0;Margin:0;padding-left:20px;padding-right:20px;padding-top:30px\">\r\n"
//        		+ "                                                <table cellpadding=\"0\" cellspacing=\"0\" class=\"esdev-mso-table\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:560px\">\r\n"
//        		+ "                                                    <tr>\r\n"
//        		+ "                                                        <td class=\"esdev-mso-td\" valign=\"top\" style=\"padding:0;Margin:0\">\r\n"
//        		+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-left\" align=\"left\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left\">\r\n"
//        		+ "                                                                <tr>\r\n"
//        		+ "                                                                    <td align=\"center\" style=\"padding:0;Margin:0;width:157px\">\r\n"
//        		+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
//        		+ "                                                                            <tr>\r\n"
//        		+ "                                                                                <td align=\"left\" style=\"padding:0;Margin:0;padding-top:5px;padding-bottom:5px\">\r\n"
//        		+ "                                                                                    <h3 class=\"p_name\" style=\"Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:20px;font-style:normal;font-weight:bold;color:#402218\">")
//        		.append(item.getProductName()).append("</h3>\r\n"
//        		+ "                                                                                </td>\r\n"
//        		+ "                                                                            </tr>\r\n"
//        		+ "                                                                        </table>\r\n"
//        		+ "                                                                    </td>\r\n"
//        		+ "                                                                </tr>\r\n"
//        		+ "                                                            </table>\r\n"
//        		+ "                                                        </td>\r\n"
//        		+ "                                                        <td style=\"padding:0;Margin:0;width:20px\"></td>\r\n"
//        		+ "                                                        <td class=\"esdev-mso-td\" valign=\"top\" style=\"padding:0;Margin:0\">\r\n"
//        		+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-left\" align=\"left\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left\">\r\n"
//        		+ "                                                                <tr>\r\n"
//        		+ "                                                                    <td align=\"center\" style=\"padding:0;Margin:0;width:94px\">\r\n"
//        		+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
//        		+ "                                                                            <tr>\r\n"
//        		+ "                                                                                <td align=\"left\" style=\"padding:0;Margin:0\">\r\n"
//        		+ "                                                                                    <p class=\"p_description\" style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:21px;color:#402218;font-size:14px\">\r\n"
//        		+ "                                                                                        Qty:<br>")
//        		.append(item.getQuantity()).append("\r\n"
//        		+ "                                                                                    </p>\r\n"
//        		+ "                                                                                </td>\r\n"
//        		+ "                                                                            </tr>\r\n"
//        		+ "                                                                        </table>\r\n"
//        		+ "                                                                    </td>\r\n"
//        		+ "                                                                </tr>\r\n"
//        		+ "                                                            </table>\r\n"
//        		+ "                                                        </td>\r\n"
//        		+ "                                                        <td style=\"padding:0;Margin:0;width:20px\"></td>\r\n"
//        		+ "                                                        <td class=\"esdev-mso-td\" valign=\"top\" style=\"padding:0;Margin:0\">\r\n"
//        		+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-left\" align=\"left\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left\">\r\n"
//        		+ "                                                                <tr>\r\n"
//        		+ "                                                                    <td align=\"left\" style=\"padding:0;Margin:0;width:135px\">\r\n"
//        		+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
//        		+ "                                                                            <tr>\r\n"
//        		+ "                                                                                <td align=\"left\" style=\"padding:0;Margin:0\">\r\n"
//        		+ "                                                                                    <p class=\"p_price\" style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:21px;color:#402218;font-size:14px\">\r\n"
//        		+ "                                                                                        Price(£):<br>")
//        		.append(item.getUnitPrice()).append("\r\n"
//        		+ "                                                                                    </p>\r\n"
//        		+ "                                                                                </td>\r\n"
//        		+ "                                                                            </tr>\r\n"
//        		+ "                                                                        </table>\r\n"
//        		+ "                                                                    </td>\r\n"
//        		+ "                                                                </tr>\r\n"
//        		+ "                                                            </table>\r\n"
//        		+ "                                                        </td>\r\n"
//        		+ "                                                        <td style=\"padding:0;Margin:0;width:20px\"></td>\r\n"
//        		+ "                                                        <td class=\"esdev-mso-td\" valign=\"top\" style=\"padding:0;Margin:0\">\r\n"
//        		+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-right\" align=\"right\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right\">\r\n"
//        		+ "                                                                <tr>\r\n"
//        		+ "                                                                    <td align=\"left\" style=\"padding:0;Margin:0;width:114px\">\r\n"
//        		+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
//        		+ "                                                                            <tr>\r\n"
//        		+ "                                                                                <td align=\"left\" style=\"padding:0;Margin:0\">\r\n"
//        		+ "                                                                                    <p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:21px;color:#402218;font-size:14px\">\r\n"
//        		+ "                                                                                        Total(£):<br>\r\n")
//        		.append(item.getItemTotal()).append("<br>\r\n"
//        		+ "                                                                                    </p>\r\n"
//        		+ "                                                                                </td>\r\n"
//        		+ "                                                                            </tr>\r\n"
//        		+ "                                                                        </table>\r\n"
//        		+ "                                                                    </td>\r\n"
//        		+ "                                                                </tr>\r\n"
//        		+ "                                                            </table>\r\n"
//        		+ "                                                        </td>\r\n"
//        		+ "                                                    </tr>\r\n"
//        		+ "                                                </table>\r\n"
//        		+ "                                            </td>\r\n"
//        		+ "                                        </tr>\r\n"
//        		+ "<!-- End Here -->\r\n");
        	
        		
        		
        		
        		
        		
        		
        		
        		
        		
        		
        		
        		
        		sb.append("\r\n"
        		+ "\r\n"
        		+ "\r\n"
        		+ "\r\n"
        		+ "\r\n"
        		+ "                                        <tr>\r\n"
        		+ "                                            <td align=\"left\" bgcolor=\"white\" style=\"padding:20px;Margin:0;background-color:white;padding-top:40px\">\r\n"
        		+ "                                                <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
        		+ "                                                    <tr>\r\n"
        		+ "                                                        <td align=\"center\" valign=\"top\" style=\"padding:0;Margin:0;width:560px\">\r\n"
        		+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
        		+ "                                                                <tr>\r\n"
        		+ "                                                                    <td align=\"left\" style=\"padding:0;Margin:0\">\r\n"
        		+ "                                                                        <h2 style=\"Margin:0;line-height:29px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:20px;font-style:normal;font-weight:bold;color:#402218\">PURCHASE SUMMARY</h2>\r\n"
        		+ "                                                                        <p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:21px;color:#402218;font-size:14px;display:none\">\r\n"
        		+ "                                                                            <br>\r\n"
        		+ "                                                                        </p>\r\n"
        		+ "                                                                    </td>\r\n"
        		+ "                                                                </tr>\r\n"
        		+ "                                                            </table>\r\n"
        		+ "                                                        </td>\r\n"
        		+ "                                                    </tr>\r\n"
        		+ "                                                </table>\r\n"
        		+ "                                            </td>\r\n"
        		+ "                                        </tr>\r\n"
        		
        		
        		
        		
        		
   
        		+ "  <tr>\r\n"
        		+ "                                             <td class=\"esdev-adapt-off\" align=\"left\" style=\"Margin:0;padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:5px\">\r\n"
        		+ "                                               <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" id=\"templateColumns\">\r\n"
        		+ "                                                   <tr>\r\n"
        		+ "                                                       <td align=\"center\" valign=\"top\" width=\"50%\" class=\"templateColumnContainer\">\r\n"
        		+ "                                                           <table border=\"0\" cellpadding=\"10\" cellspacing=\"0\" width=\"100%\">\r\n"
        		+ "                                                             <tr>\r\n"
        		+ "                                                                 <td>\r\n"
        		+ "                                                                   <p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:21px;color:#402218;font-size:14px\">\r\n"
        		+ "                                                                       Subtotal(£):\r\n"
        		+ "                                                                   </p>\r\n"
        		+ "                                                                 </td>\r\n"
        		+ "                                                                 <td style=\"text-align:right\">\r\n"
        		+ "                                                                   <p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:21px;color:#402218;font-size:14px\">\r\n")
        		.append(totalPrice).append("</p>\r\n"
        		+ "                                                                 </td>\r\n"
        		+ "                                                             </tr>\r\n"
        		+ "                                                             <tr>\r\n"
        		+ "                                                                 <td>\r\n"
        		+ "                                                                   <p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:21px;color:#402218;font-size:14px\">\r\n"
        		+ "                                                                       Shipping(£):\r\n"
        		+ "                                                                   </p>\r\n"
        		+ "                                                                 </td>\r\n"
        		+ "                                                                 <td style=\"text-align:right\">\r\n"
        		+ "                                                                   <p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:21px;color:#402218;font-size:14px\">\r\n"
        		+ "                                                                       0.00\r\n"
        		+ "                                                                   </p>\r\n"
        		+ "                                                                 </td>\r\n"
        		+ "                                                             </tr>\r\n"
        		+ "                                                             <tr>\r\n"
        		+ "                                                                 <td >\r\n"
        		+ "                                                                   <p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:21px;color:#402218;font-size:14px\">\r\n"
        		+ "                                                                       Tax(£):\r\n"
        		+ "                                                                   </p>\r\n"
        		+ "                                                                 </td>\r\n"
        		+ "\r\n"
        		+ "                                                                 <td style=\"text-align:right\">\r\n"
        		+ "                                                                   <p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:21px;color:#402218;font-size:14px\">\r\n"
        		+ "                                                                       0.00\r\n"
        		+ "                                                                   </p>\r\n"
        		+ "                                                                 </td>\r\n"
        		+ "                                                             </tr>\r\n"
        		+ "                                                             <tr>\r\n"
        		+ "                                                                 <td>\r\n"
        		+ "                                                                  <p style=\"Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:16px;font-style:normal;font-weight:bold;color:#402218\">Order Total(£):</p>\r\n"
        		+ "                                                                 </td>\r\n"
        		+ "                                                                 <td style=\"text-align:right\">\r\n"
        		+ "                                                                <p style=\"Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:16px;font-style:normal;font-weight:bold;color:#402218\">")
        		.append(totalPrice).append("</p>\r\n"
        		+ "                                                                 </td>\r\n"
        		+ "                                                             </tr>\r\n"
        		+ "                                               </table>\r\n"
        		+ "                                             </td>\r\n"
        		+ "                                      </tr>"
        		
        		
        		





        		
        		
        		
//        		+ "                                        <tr>\r\n"
//        		+ "                                            <td class=\"esdev-adapt-off\" align=\"left\" style=\"Margin:0;padding-bottom:20px;padding-left:20px;padding-right:20px;padding-top:5px\">\r\n"
//        		+ "                                                <table cellpadding=\"0\" cellspacing=\"0\" class=\"esdev-mso-table\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:560px\">\r\n"
//        		+ "                                                    <tr>\r\n"
//        		+ "                                                        <td class=\"esdev-mso-td\" valign=\"top\" style=\"padding:0;Margin:0\">\r\n"
//        		+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-left\" align=\"left\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:left\">\r\n"
//        		+ "                                                                <tr>\r\n"
//        		+ "                                                                    <td align=\"center\" style=\"padding:0;Margin:0;width:435px\">\r\n"
//        		+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
//        		+ "                                                                            <tr>\r\n"
//        		+ "                                                                                <td align=\"left\" class=\"es-m-txt-l\" style=\"padding:0;Margin:0\">\r\n"
//        		+ "                                                                                    <p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:21px;color:#402218;font-size:14px\">\r\n"
//        		+ "                                                                                        Subtotal(£):<br>Shipping(£):\r\n"
//        		+ "                                                                                    </p>\r\n"
//        		+ "                                                                                    <p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:21px;color:#402218;font-size:14px\">Tax(£):</p>\r\n"
//        		+ "                                                                                    <h3 style=\"Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:20px;font-style:normal;font-weight:bold;color:#402218\">Order Total(£):</h3>\r\n"
//        		+ "                                                                                </td>\r\n"
//        		+ "                                                                            </tr>\r\n"
//        		+ "                                                                        </table>\r\n"
//        		+ "                                                                    </td>\r\n"
//        		+ "                                                                </tr>\r\n"
//        		+ "                                                            </table>\r\n"
//        		+ "                                                        </td>\r\n"
//        		+ "                                                        <td style=\"padding:0;Margin:0;width:20px\"></td>\r\n"
//        		+ "                                                        <td class=\"esdev-mso-td\" valign=\"top\" style=\"padding:0;Margin:0\">\r\n"
//        		+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-right\" align=\"right\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;float:right\">\r\n"
//        		+ "                                                                <tr>\r\n"
//        		+ "                                                                    <td align=\"left\" style=\"padding:0;Margin:0;width:105px\">\r\n"
//        		+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
//        		+ "                                                                            <tr>\r\n"
//        		+ "                                                                                <td align=\"left\" style=\"padding:0;Margin:0\">\r\n"
//        		+ "                                                                                    <p class=\"p_price\" style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:21px;color:#402218;font-size:14px\">\r\n")
//        		.append(totalPrice).append("<br>\r\n"
//        		+ "                                                                                        00.00<br>00.00\r\n"
//        		+ "                                                                                    </p>\r\n"
//        		+ "                                                                                    <h3 class=\"p_price\" style=\"Margin:0;line-height:24px;mso-line-height-rule:exactly;font-family:Oswald, sans-serif;font-size:20px;font-style:normal;font-weight:bold;color:#402218\">\r\n")
//        		.append(totalPrice).append("<br>\r\n"
//        		+ "                                                                                    </h3>\r\n"
//        		+ "                                                                                </td>\r\n"
//        		+ "                                                                            </tr>\r\n"
//        		+ "                                                                        </table>\r\n"
//        		+ "                                                                    </td>\r\n"
//        		+ "                                                                </tr>\r\n"
//        		+ "                                                            </table>\r\n"
//        		+ "                                                        </td>\r\n"
//        		+ "                                                    </tr>\r\n"
//        		+ "                                                </table>\r\n"
//        		+ "                                            </td>\r\n"
//        		+ "                                        </tr>\r\n"
        		
        		
        		
        		
        		
        		
        		
        		+ "                                    </table>\r\n"
        		+ "                                </td>\r\n"
        		+ "                            </tr>\r\n"
        		+ "                        </table>\r\n"
        		+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer\" align=\"center\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top\">\r\n"
        		+ "                            <tr>\r\n"
        		+ "                                <td align=\"center\" style=\"padding:0;Margin:0\">\r\n"
        		+ "                                    <table class=\"es-footer-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#ffffff;width:600px\" bgcolor=\"#ffffff\">\r\n"
        		+ "                                        <tr>\r\n"
        		+ "                                            <td align=\"left\" style=\"Margin:0;padding-top:20px;padding-bottom:20px;padding-left:20px;padding-right:20px\">\r\n"
        		+ "                                                <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
        		+ "                                                    <tr>\r\n"
        		+ "                                                        <td align=\"left\" style=\"padding:0;Margin:0;width:560px\">\r\n"
        		+ "                                                            <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
        		+ "                                                                <tr>\r\n"
        		+ "                                                                    <td style=\"padding:0;Margin:0\">\r\n"
        		+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"es-menu\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
        		+ "                                                                            <tr class=\"links\">\r\n"
        		+ "                                                                                <td align=\"center\" valign=\"top\" width=\"25%\" id=\"esd-menu-id-0\" style=\"Margin:0;padding-left:5px;padding-right:5px;padding-top:10px;padding-bottom:10px;border:0\">\r\n"
        		+ "                                                                                    <a target=\"_blank\" href=\"https://madhurams.co.uk/index\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;display:block;font-family:arial, 'helvetica neue', helvetica, sans-serif;color:#402218;font-size:14px\">About us</a>\r\n"
        		+ "                                                                                </td>\r\n"
        		+ "                                                                                <td align=\"center\" valign=\"top\" width=\"25%\" id=\"esd-menu-id-1\" style=\"Margin:0;padding-left:5px;padding-right:5px;padding-top:10px;padding-bottom:10px;border:0\">\r\n"
        		+ "                                                                                    <a target=\"_blank\" href=\"https://madhurams.co.uk/contact\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;display:block;font-family:arial, 'helvetica neue', helvetica, sans-serif;color:#402218;font-size:14px\">News</a>\r\n"
        		+ "                                                                                </td>\r\n"
        		+ "                                                                                <td align=\"center\" valign=\"top\" width=\"25%\" id=\"esd-menu-id-2\" style=\"Margin:0;padding-left:5px;padding-right:5px;padding-top:10px;padding-bottom:10px;border:0\">\r\n"
        		+ "                                                                                    <a target=\"_blank\" href=\"https://madhurams.co.uk/contact\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;display:block;font-family:arial, 'helvetica neue', helvetica, sans-serif;color:#402218;font-size:14px\">Contact</a>\r\n"
        		+ "                                                                                </td>\r\n"
        		+ "                                                                                <td align=\"center\" valign=\"top\" width=\"25%\" id=\"esd-menu-id-2\" style=\"Margin:0;padding-left:5px;padding-right:5px;padding-top:10px;padding-bottom:10px;border:0\">\r\n"
        		+ "                                                                                    <a target=\"_blank\" href=\"https://madhurams.co.uk/shop\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:none;display:block;font-family:arial, 'helvetica neue', helvetica, sans-serif;color:#402218;font-size:14px\">shop</a>\r\n"
        		+ "                                                                                </td>\r\n"
        		+ "                                                                            </tr>\r\n"
        		+ "                                                                        </table>\r\n"
        		+ "                                                                    </td>\r\n"
        		+ "                                                                </tr>\r\n"
        		+ "                                                              <!--  <tr>\r\n"
        		+ "                                                                    <td align=\"center\" style=\"padding:0;Margin:0;padding-top:10px;padding-bottom:10px;font-size:0\">\r\n"
        		+ "                                                                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-table-not-adapt es-social\" role=\"presentation\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
        		+ "                                                                            <tr>\r\n"
        		+ "                                                                                <td align=\"center\" valign=\"top\" style=\"padding:0;Margin:0;padding-right:20px\">\r\n"
        		+ "                                                                                    <a target=\"_blank\" href=\"https://viewstripo.email\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#402218;font-size:14px\">\r\n"
        		+ "                                                                                        <img title=\"Facebook\" src=\"images/facebook-logo-colored.png\" alt=\"Fb\" width=\"24\" height=\"24\" style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic\">\r\n"
        		+ "                                                                                    </a>\r\n"
        		+ "                                                                                </td>\r\n"
        		+ "                                                                                <td align=\"center\" valign=\"top\" style=\"padding:0;Margin:0;padding-right:20px\">\r\n"
        		+ "                                                                                    <a target=\"_blank\" href=\"https://viewstripo.email\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#402218;font-size:14px\">\r\n"
        		+ "                                                                                        <img title=\"Twitter\" src=\"images/twitter-logo-colored.png\" alt=\"Tw\" width=\"24\" height=\"24\" style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic\">\r\n"
        		+ "                                                                                    </a>\r\n"
        		+ "                                                                                </td>\r\n"
        		+ "                                                                                <td align=\"center\" valign=\"top\" style=\"padding:0;Margin:0;padding-right:20px\">\r\n"
        		+ "                                                                                    <a target=\"_blank\" href=\"https://viewstripo.email\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#402218;font-size:14px\">\r\n"
        		+ "                                                                                        <img title=\"Instagram\" src=\"images/instagram-logo-colored.png\" alt=\"Inst\" width=\"24\" height=\"24\" style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic\">\r\n"
        		+ "                                                                                    </a>\r\n"
        		+ "                                                                                </td>\r\n"
        		+ "                                                                                <td align=\"center\" valign=\"top\" style=\"padding:0;Margin:0\">\r\n"
        		+ "                                                                                    <a target=\"_blank\" href=\"https://viewstripo.email\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#402218;font-size:14px\">\r\n"
        		+ "                                                                                        <img title=\"Youtube\" src=\"images/youtube-logo-colored.png\" alt=\"Yt\" width=\"24\" height=\"24\" style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic\">\r\n"
        		+ "                                                                                    </a>\r\n"
        		+ "                                                                                </td>\r\n"
        		+ "                                                                            </tr>\r\n"
        		+ "                                                                        </table>\r\n"
        		+ "                                                                    </td>\r\n"
        		+ "                                                                </tr> -->\r\n"
        		+ "\r\n"
        		+ "\r\n"
        		+ "                                                                <tr>\r\n"
        		+ "                                                                    <td align=\"center\" style=\"padding:0;Margin:0;padding-top:10px;padding-bottom:10px\">\r\n"
        		+ "                                                                        <p style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';line-height:18px;color:#402218;font-size:12px\">\r\n"
        		+ "                                                                            <!--You are receiving this email because you have visited our site or asked us about the regular newsletter. Make sure our messages get to your Inbox (and not your bulk or junk folders)-->.<br>\r\n"
        		+ "                                                                            <strong>\r\n"
        		+ "                                                                                <a target=\"_blank\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#402218;font-size:12px\" href=\"https://localhost:8080/privacy\">Privacy policy</a>\r\n"
        		+ "                                                                                | <a target=\"_blank\" style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#402218;font-size:12px\" href=\"\">Terms</a>\r\n"
        		+ "                                                                            </strong>\r\n"
        		+ "                                                                        </p>\r\n"
        		+ "                                                                    </td>\r\n"
        		+ "                                                                </tr>\r\n"
        		+ "                                                            </table>\r\n"
        		+ "                                                        </td>\r\n"
        		+ "                                                    </tr>\r\n"
        		+ "                                                </table>\r\n"
        		+ "                                            </td>\r\n"
        		+ "                                        </tr>\r\n"
        		+ "                                    </table>\r\n"
        		+ "                                </td>\r\n"
        		+ "                            </tr>\r\n"
        		+ "                        </table>\r\n"
        		+ "                        <table cellpadding=\"0\" cellspacing=\"0\" class=\"es-footer\" align=\"center\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top\">\r\n"
        		+ "                            <tr>\r\n"
        		+ "                                <td align=\"center\" style=\"padding:0;Margin:0\">\r\n"
        		+ "                                    <table class=\"es-footer-body\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px\">\r\n"
        		+ "                                        <tr>\r\n"
        		+ "                                            <td align=\"left\" style=\"Margin:0;padding-top:20px;padding-bottom:20px;padding-left:20px;padding-right:20px\">\r\n"
        		+ "\r\n"
        		+ "                                            </td>\r\n"
        		+ "                                        </tr>\r\n"
        		+ "                                    </table>\r\n"
        		+ "                                </td>\r\n"
        		+ "                            </tr>\r\n"
        		+ "                        </table>\r\n"
        		+ "                    </td>\r\n"
        		+ "                </tr>\r\n"
        		+ "            </table>\r\n"
        		+ "        </div>\r\n"
        		+ "    </body>\r\n"
        		+ "</html>\r\n"
        		+ "");
        
        
        
//        sb.append("<html><body>");
//        sb.append("<h3>Order Confirmation</h3>");
//        sb.append("<p>Dear Customer,</p>");
//        sb.append("<p>Your order with order number ").append(orderNumber).append(" has been confirmed. Thank you for shopping with us.</p>");
//        sb.append("<table border=\"1\">");
//        sb.append("<tr><th>Item</th><th>Quantity</th><th>Price</th></tr>");
//        for (OrderSummary item : orderItems) {
//            //sb.append("<tr><td>").append(item.getName()).append("</td><td>").append(item.getQuantity()).append("</td><td>").append(item.getPrice()).append("</td></tr>");
//        }
//        sb.append("<tr><td colspan=\"2\">Total Price:</td><td>").append(totalPrice).append("</td></tr>");
//        sb.append("</table>");
//        sb.append("<p>Regards,<br>The Store Team</p>");
//        sb.append("</body></html>");
        System.out.println(sb.toString());
        return sb.toString();
    }

}
